### ISSUE TITLE
Saving Pricelist Fatal Error

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#837]
If you delete all terms from a Pricelist and then add terms back and click save, you get a fatal error:

```
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /app/public/wp-content/plugins/sell-media/inc/class-price-listings-tabs.php:259 Stack trace: #0 /app/public/wp-includes/class-wp-hook.php(286): Sell_Media_Price_Listings_Tabs->save_data('http://sellmedi...') #1 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /app/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /app/public/wp-content/plugins/sell-media/inc/class-price-listings.php(145): do_action('sell_media_pric...', 'http://sellmedi...') #4 /app/public/wp-includes/class-wp-hook.php(286): Sell_Media_Price_Listings->load_pricelists_page('') #5 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /app/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /app/public/wp-admin/admin.php(214): do_action('load-sell_media...') #8 /app/public/wp-admin/edit.php(10): require_once('/app/public/wp-...') #9 {main} thrown in /app/public/wp-content/plugins/sell-media/inc/class-price-listings-tabs.php on line 259
```

<img width="883" alt="screen shot 2018-01-10 at 4 33 14 pm" src="https://user-images.githubusercontent.com/302884/34796694-4abf5538-f624-11e7-961a-3bd23cacc9cf.png">

**Comment by rickalday** [comment]
Fixed in 83fd0b8b7786f1655331dc7b0a1aab07c7b63e0d
